language: node_js
node_js:
- 5.0.0
sudo: false
env:
  matrix:
  - GROUP=
  global:
  - GH_REF: github.com/jupyter/jupyter-js-filebrowser.git
  - secure: HT4gliJbIUE0k1wsSJEiLoTtqgvhqvfFWMf8PieC+8CC+XYX/C5HgCcai3dwKoz+OXpLTl4wFA7rzCtZvC0HRXQ4lCvWbLFXiYPtoLC8uP/QOBlqEPeqLPSXlnbWZGlU0XEasCvmF+BTeOh/nH9/2V/RNQ1iCN0Cy5Pbk829K6WL/95gn9KRUPwvtCsAEGblhEMbAednqh5aNgsQC8Q83BlY+lgXrrO87KbVl+3tbFuWYBWCRO/pXwmX2Kki3l588sQr7+/BnIAeDphchxMn/VmDBBrXPzFWcL/Av6cVimxdOMy8Zy1NZwrxOGzPPBf8PdYr1HlE4hr8wv34kDwAiXQvcsPO4GYeZxDyp+RARxoNcgwihpNeGFjYc95I/qjM3C4dAOtNSg60o4L/6I/nZEwp7Wlz9dN4pLemjaGpDy+wS2RDmfCary/dAL4sqcP8ExsGi2n8SgWysJlkH2bgS5cxKgsopeasicO9JOJdqvd/XQbF72o1uSgWvHHpx5dEsR88ijXnu1GOpR2Ck8e/apuLxXq9Xpdsmb/BJBqYRYUYd3Y8hNRf/8YU0C8wol4wG1CKrJs3D2SzyirLI1uNTN+CXTV5IUuW2D0Wwd9RSgQrbyiRgYl2ua/HWlgcAkhpaao97ONDOTxgr3jY65Twy00AT8f6NmlswSc49N1XRzE=
install:
- bash ./scripts/travis_install.sh
script:
- bash ./scripts/travis_script.sh
after_success:
- bash ./scripts/travis_after_success.sh
